### ISSUE TITLE
Java.Lang.NullPointerException on start

### ISSUE THREAD

**Issue by xakpc** [dbeattie71/SnackbarSharp#1]
When i add your library to Android project with MVVMCross installed app refuse to start with Java.Lang.NullPointerException. What can cause this issue?

Log

`````` Text

Unhandled Exception:

Java.Lang.NullPointerException: 

01-28 14:27:39.289 D/Mono    ( 2371): DllImport attempting to load: '/system/lib/liblog.so'.
01-28 14:27:39.289 D/Mono    ( 2371): DllImport loaded library '/system/lib/liblog.so'.
01-28 14:27:39.289 D/Mono    ( 2371): DllImport searching in: '/system/lib/liblog.so' ('/system/lib/liblog.so').
01-28 14:27:39.289 D/Mono    ( 2371): Searching for '__android_log_print'.
01-28 14:27:39.289 D/Mono    ( 2371): Probing '__android_log_print'.
01-28 14:27:39.289 D/Mono    ( 2371): Found as '__android_log_print'.
An unhandled exception occured.

01-28 14:27:39.293 I/MonoDroid( 2371):  at fines.droid.views.EnterFirstAutoView.onCreate(Enter01-28 14:27:39.293 I/MonoDroid( 2371): UNHANDLED EXCEPTION:
01-28 14:27:39.293 I/MonoDroid( 2371): Java.Lang.NullPointerException: Exception of type 'Java.Lang.NullPointerException' was thrown.
01-28 14:27:39.293 I/MonoDroid( 2371): at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () <IL 0x00011, 0x00047>
01-28 14:27:39.293 I/MonoDroid( 2371): at Android.Runtime.JNIEnv.CallNonvirtualVoidMethod (intptr,intptr,intptr,Android.Runtime.JValue[]) [0x00084] in /Users/builder/data/lanes/monodroid-mlion-monodroid-4.21-series/49a04b96/source/monodroid/src/Mono.Android/src/Runtime/JNIEnv.g.cs:896
01-28 14:27:39.293 I/MonoDroid( 2371): at Android.App.Activity.SetContentView (Android.Views.View) [0x00070] in /Users/builder/data/lanes/monodroid-mlion-monodroid-4.21-series/49a04b96/source/monodroid/src/Mono.Android/platforms/android-21/src/generated/Android.App.Activity.cs:4701
01-28 14:27:39.293 I/MonoDroid( 2371): at Fines.Droid.Views.MvxActionBarActivity.SetContentView (int) [0x0000a] in c:\Users\xakpc\Documents\GitHub\Fines.Apps\Fines.Droid\Views\MvxActionBarActivity.cs:61
01-28 14:27:39.293 I/MonoDroid( 2371): at Fines.Droid.Views.EnterFirstAutoView.OnCreate (Android.OS.Bundle) [0x00009] in c:\Users\xakpc\Documents\GitHub\Fines.Apps\Fines.Droid\Views\EnterFirstAutoView.cs:33
01-28 14:27:39.293 I/MonoDroid( 2371): at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_ (intptr,intptr,intptr) [0x00011] in /Users/builder/data/lanes/monodroid-mlion-monodroid-4.21-series/49a04b96/source/monodroid/src/Mono.Android/platforms/android-21/src/generated/Android.App.Activity.cs:2380
01-28 14:27:39.293 I/MonoDroid( 2371): at (wrapper dynamic-method) object.ad326a52-ef14-4511-ab29-8775dc5a6076 (intptr,intptr,intptr) <IL 0x00017, 0x0001f>
01-28 14:27:39.293 I/MonoDroid( 2371):   --- End of managed exception stack trace ---
01-28 14:27:39.293 I/MonoDroid( 2371): java.lang.NullPointerException
01-28 14:27:39.293 I/MonoDroid( 2371):  at android.support.v7.app.ActionBarActivityDelegateBase.ensureSubDecor(ActionBarActivityDelegateBase.java:346)
01-28 14:27:39.293 I/MonoDroid( 2371):  at android.support.v7.app.ActionBarActivityDelegateBase.setContentView(ActionBarActivityDelegateBase.java:216)
01-28 14:27:39.293 I/MonoDroid( 2371):  at android.support.v7.app.ActionBarActivity.setContentView(ActionBarActivity.java:107)
01-28 14:27:39.293 I/MonoDroid( 2371):  at fines.droid.views.EnterFirstAutoView.n_onCreate(Native Method)
01-28 14:27:39.293 I/MonoDroid( 2371):  at fines.droid.views.EnterFirstAutoView.onCreate(EnterFirstAutoView.java:28)
01-28 14:27:39.293 I/MonoDroid( 2371):  at android.app.Activity.performCreate(Activity.java:5104)
01-28 14:27:39.293 I/MonoDroid( 2371):  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1080)
01-28 14:27:39.293 I/MonoDroid( 2371):  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2144)
01-28 14:27:39.293 I/MonoDroid( 2371):  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2230)
01-28 14:27:39.293 I/MonoDroid( 2371):  at android.app.ActivityThread.access$600(ActivityThread.java:141)
01-28 14:27:39.293 I/MonoDroid( 2371):  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1234)
01-28 14:27:39.293 I/MonoDroid( 2371):  at android.os.Handler.dispatchMessage(Handler.java:99)
01-28 14:27:39.293 I/MonoDroid( 2371):  at android.os.Looper.loop(Looper.java:137)
01-28 14:27:39.293 I/MonoDroid( 2371):  at android.app.ActivityThread.main(ActivityThread.java:5041)
01-28 14:27:39.293 I/MonoDroid( 2371):  at java.lang.reflect.Method.invokeNative(Native Method)
01-28 14:27:39.293 I/MonoDroid( 2371):  at java.lang.reflect.Method.invoke(Method.java:511)
01-28 14:27:39.293 I/MonoDroid( 2371):  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
01-28 14:27:39.293 I/MonoDroid( 2371):  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
01-28 14:27:39.293 I/MonoDroid( 2371):  at dalvik.system.NativeStart.main(Native Method)
01-28 14:27:41.661 E/mono    ( 2371): 
01-28 14:27:41.661 E/mono    ( 2371): Unhandled Exception:
01-28 14:27:41.661 E/mono    ( 2371): Java.Lang.NullPointerException: Exception of type 'Java.Lang.NullPointerException' was thrown.
01-28 14:27:41.661 E/mono    ( 2371): at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () <IL 0x00011, 0x00047>
01-28 14:27:41.661 E/mono    ( 2371): at Android.Runtime.JNIEnv.CallNonvirtualVoidMethod (intptr,intptr,intptr,Android.Runtime.JValue[]) [0x00084] in /Users/builder/data/lanes/monodroid-mlion-monodroid-4.21-series/49a04b96/source/monodroid/src/Mono.Android/src/Runtime/JNIEnv.g.cs:896
01-28 14:27:41.661 E/mono    ( 2371): at Android.App.Activity.SetContentView (Android.Views.View) [0x00070] in /Users/builder/data/lanes/monodroid-mlion-monodroid-4.21-series/49a04b96/source/monodroid/src/Mono.Android/platforms/android-21/src/generated/Android.App.Activity.cs:4701
The program 'Mono' has exited with code 0 (0x0). ```
``````

**Comment by dbeattie71** [comment]
I use it with MvvmCross too.  How are you calling it?  Are you using the manager?

**Comment by xakpc** [comment]
Yes, of course. But apps crashes on start.
I also use AppCompat v21

i will create test project and publish it later

**Comment by dbeattie71** [comment]
With latest, let me know if this still happens.
